development:
  adapter: postgresql
  encoding: unicode
  database: energie_development
  pool: 5
  host: localhost
  username: postgres
  password: taL94539

production:
  adapter: postgresql
  encoding: unicode
  database: energie_production
  pool: 5
  host: localhost
  username: postgres
  password: taL94539
